### ISSUE TITLE
Cannot find module when running 'init'

### ISSUE THREAD

**Issue by pthomas931** [jfehrman/decision_json#2]
Unable to get `init` command to work. Currently receiving a module not found for `app-init`. I've attempted running init from the root, src, and dist directories. 

Error:
```
$ decision_json init -f test.json
module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\Projects\decision_json\app-init'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Environment:
- Windows 10 Pro
- node v8.9.4
- npm 5.8.0

**Comment by cogwizzle** [comment]
If I remember this correctly I think I need to rename some of the JavaScript files so Windows recognizes them.  I will add this to the list of things to do.
